[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-True {
    param([bool] $Condition, [string] $Because)
    if (-not $Condition) { throw "Assertion failed: $Because" }
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
. (Join-Path $repositoryRoot 'build/TextCanonicalization.ps1')
$buildScript = Join-Path $repositoryRoot 'build/Build.ps1'
$outputDirectory = Join-Path $repositoryRoot '.test-output/build-determinism'
$firstPath = Join-Path $outputDirectory 'first/WIN-PCInfo.ps1'
$secondPath = Join-Path $outputDirectory 'second/WIN-PCInfo.ps1'

$first = & $buildScript -OutputPath $firstPath
$second = & $buildScript -OutputPath $secondPath
$firstBytes = [System.IO.File]::ReadAllBytes($firstPath)
$secondBytes = [System.IO.File]::ReadAllBytes($secondPath)

Assert-True ([System.Linq.Enumerable]::SequenceEqual[byte]($firstBytes, $secondBytes)) `
    'the same modular source must produce identical generated bytes in different output directories'
Assert-True ($first.sha256 -eq $second.sha256) 'the deterministic artifact digest must agree'
Assert-True ($first.buildContract -eq 'win-pcinfo.build-evidence/1.0.0') 'build evidence is versioned'
Assert-True ($first.buildTool.path -eq 'build/Build.ps1') 'the build tool has a normalized repository identity'
Assert-True ($first.buildTool.sha256 -match '^[0-9a-f]{64}$') 'the build tool digest is exact'
$expectedSourcePaths = @(
    'src/ApplicationHeader.ps1'
    'src/Contracts.ps1'
    'src/ContractValidator.ps1'
    'src/RuntimeCompatibility.ps1'
    'src/Preparation.ps1'
    'src/ProcessSupervisor.ps1'
    'src/FirmwareReadiness.ps1'
    'src/PrivilegedCollectionPlan.ps1'
    'src/SystemCollectionPlan.ps1'
    'src/IdentityEnrollment.ps1'
    'src/AdministratorExposure.ps1'
    'src/EffectivePolicy.ps1'
    'src/ResourceDependencies.ps1'
    'src/NetworkTopology.ps1'
    'src/SoftwareInventory.ps1'
    'src/CertificateTrust.ps1'
    'src/MicrosoftConnectivity.ps1'
    'src/SoftwareRecognition.ps1'
    'src/CrossDomainGuidance.ps1'
    'src/EvidenceWorkspace.ps1'
    'src/RecipientSharing.ps1'
    'src/ProtectedPackage.ps1'
    'src/DeviceReadiness.ps1'
    'src/RunLifecycle.ps1'
    'src/LaunchEngine.ps1'
    'src/EntryAdapters.ps1'
    'src/ProductHelp.ps1'
    'src/PortableDistribution.ps1'
    'src/AttestedPreview.ps1'
    'src/AzureValidationAdmission.ps1'
    'src/AzureValidationRound.ps1'
    'src/ReleaseGates.ps1'
    'src/SigningBoundary.ps1'
    'src/PreviewQualification.ps1'
    'src/ApplicationMain.ps1'
)
Assert-True ((@($first.sourceInputs.path | Sort-Object) -join '|') -eq
    (@($expectedSourcePaths | Sort-Object) -join '|')) `
    'the exact modular source set is recorded'
Assert-True (@($first.sourceInputs | Where-Object { $_.sha256 -notmatch '^[0-9a-f]{64}$' }).Count -eq 0) `
    'every modular source input has an exact digest'
Assert-True ($first.definitionInputs.Count -eq 3) 'all governing preparation resources are recorded'
Assert-True (@($first.definitionInputs | Where-Object { $_.sha256 -notmatch '^[0-9a-f]{64}$' }).Count -eq 0) `
    'every governing preparation resource has an exact digest'
$expectedApplicationResourcePaths = @($expectedSourcePaths) + @(
    'build/Build.ps1'
    'build/TextCanonicalization.ps1'
    'build/DeterministicArchive.ps1'
    'build/PortableDistribution.ps1'
    'build/AttestedPreview.ps1'
    'build/Attest-Preview.ps1'
    'build/Start-WIN-PCInfo.ps1'
    'schemas/assessment-run-request.schema.json'
    'schemas/preparation-plan.schema.json'
    'schemas/assessment-record.schema.json'
    'schemas/assessment-contract-set.schema.json'
    'schemas/approved-collector-catalog.schema.json'
    'schemas/run-lifecycle.schema.json'
    'schemas/privileged-collection-plan.schema.json'
    'schemas/system-collection-plan.schema.json'
    'schemas/evidence-workspace.schema.json'
    'schemas/run-recovery-journal.schema.json'
    'schemas/protected-package.schema.json'
    'schemas/protected-package-envelope.schema.json'
    'schemas/assessment-package-manifest.schema.json'
    'schemas/recipient-profile.schema.json'
    'schemas/recipient-sharing.schema.json'
    'schemas/device-readiness.schema.json'
    'schemas/firmware-readiness.schema.json'
    'schemas/identity-enrollment.schema.json'
    'schemas/administrator-exposure.schema.json'
    'schemas/effective-policy.schema.json'
    'schemas/resource-dependencies.schema.json'
    'schemas/network-topology.schema.json'
    'schemas/software-inventory.schema.json'
    'schemas/certificate-trust.schema.json'
    'schemas/microsoft-connectivity.schema.json'
    'schemas/cross-domain-guidance.schema.json'
    'schemas/guided-runway.schema.json'
    'schemas/portable-distribution.schema.json'
    'schemas/attested-preview.schema.json'
    'schemas/attested-preview-attestation.schema.json'
    'schemas/azure-validation-admission.schema.json'
    'schemas/azure-validation-round-request.schema.json'
    'schemas/azure-validation-admission-verdict.schema.json'
    'schemas/azure-validation-round.schema.json'
    'schemas/azure-validation-round-execution-request.schema.json'
    'schemas/azure-validation-round-outcome.schema.json'
    'schemas/release-gates.schema.json'
    'schemas/signing-boundary.schema.json'
    'schemas/signing-session-request.schema.json'
    'schemas/signing-session-result.schema.json'
    'schemas/preview-qualification.schema.json'
    'schemas/preview-qualification-request.schema.json'
    'schemas/preview-qualification-packet.schema.json'
    'schemas/release-evidence-pack.schema.json'
    'schemas/release-evidence-manifest.schema.json'
    'schemas/preview-capability-matrix.schema.json'
    'schemas/software-recognition-catalog.schema.json'
    'docs/spec/releases/2.0.0-preview.1-contract-set.json'
    'docs/spec/releases/2.0.0-preview.1-approved-collectors.json'
    'docs/spec/releases/2.0.0-preview.1-run-lifecycle.json'
    'docs/spec/releases/2.0.0-preview.1-privileged-collection-plan.json'
    'docs/spec/releases/2.0.0-preview.1-system-collection-plan.json'
    'docs/spec/releases/2.0.0-preview.1-evidence-workspace.json'
    'docs/spec/releases/2.0.0-preview.1-protected-package.json'
    'docs/spec/releases/2.0.0-preview.1-recipient-sharing.json'
    'docs/spec/releases/2.0.0-preview.1-device-readiness.json'
    'docs/spec/releases/2.0.0-preview.1-firmware-readiness.json'
    'docs/spec/releases/2.0.0-preview.1-identity-enrollment.json'
    'docs/spec/releases/2.0.0-preview.1-administrator-exposure.json'
    'docs/spec/releases/2.0.0-preview.1-effective-policy.json'
    'docs/spec/releases/2.0.0-preview.1-resource-dependencies.json'
    'docs/spec/releases/2.0.0-preview.1-network-topology.json'
    'docs/spec/releases/2.0.0-preview.1-software-inventory.json'
    'docs/spec/releases/2.0.0-preview.1-certificate-trust.json'
    'docs/spec/releases/2.0.0-preview.1-microsoft-connectivity.json'
    'docs/spec/releases/2.0.0-preview.1-cross-domain-guidance.json'
    'docs/spec/releases/2.0.0-preview.1-guided-runway.json'
    'docs/spec/releases/2.0.0-preview.1-portable-distribution.json'
    'docs/spec/releases/2.0.0-preview.1-attested-preview.json'
    'docs/spec/releases/2.0.0-preview.1-azure-validation-admission.json'
    'docs/spec/releases/2.0.0-preview.1-azure-validation-round.json'
    'docs/spec/releases/2.0.0-preview.1-release-gates.json'
    'docs/spec/releases/2.0.0-preview.1-signing-boundary.json'
    'docs/spec/releases/2.0.0-preview.1-preview-qualification.json'
    'docs/spec/releases/2.0.0-preview.1-software-recognition-catalog.json'
)
Assert-True ((@($first.applicationManifest.resources.path | Sort-Object) -join '|') -eq
    (@($expectedApplicationResourcePaths | Sort-Object) -join '|')) `
    'the exact source, build tool, public schema, and release Contract Set resources are bound into the application manifest'
Assert-True ($first.applicationManifest.sha256 -match '^[0-9a-f]{64}$') `
    'the application manifest has one exact digest'
foreach ($resource in @($first.applicationManifest.resources) + @($first.definitionInputs)) {
    $resourcePath = Join-Path $repositoryRoot $resource.path
    $utf8LfBytes = Get-Utf8LfBytes -LiteralPath $resourcePath
    $utf8LfDigest = [System.Convert]::ToHexString(
        [System.Security.Cryptography.SHA256]::HashData($utf8LfBytes)
    ).ToLowerInvariant()
    Assert-True ($resource.sha256 -eq $utf8LfDigest) `
        "$($resource.path) uses a checkout-independent UTF-8/LF identity"
}

$vectorPath = Join-Path $outputDirectory 'canonicalization-vector.txt'
[System.IO.File]::WriteAllText($vectorPath, "alpha`r`nbeta`rgamma`n", [System.Text.UTF8Encoding]::new($false))
[byte[]] $expectedVector = [System.Text.UTF8Encoding]::new($false).GetBytes("alpha`nbeta`ngamma`n")
[byte[]] $actualVector = @(Get-Utf8LfBytes $vectorPath)
Assert-True ([System.Linq.Enumerable]::SequenceEqual[byte]($actualVector, $expectedVector)) `
    'UTF-8/LF identity normalizes CRLF and bare CR without adding a BOM'

$mirrorSessionRoot = Join-Path $outputDirectory ([System.Guid]::NewGuid().ToString('N'))
$packageDocumentPaths = @(
    'SECURITY.md'
    'CONTRIBUTING.md'
)
$docsRoot = Join-Path $repositoryRoot 'docs'
foreach ($document in @(Get-ChildItem -LiteralPath $docsRoot -File -Recurse | Sort-Object FullName)) {
    if ($document.Extension -notin @('.md', '.json')) { continue }
    $relative = $document.FullName.Substring($docsRoot.Length).TrimStart('\', '/').Replace('\', '/')
    $top = ($relative -split '/')[0]
    if ($top -in @('validation', 'research')) { continue }
    $packageDocumentPaths += "docs/$relative"
}
$mirrorResources = @(
    @($first.applicationManifest.resources.path) + @($first.definitionInputs.path) + $packageDocumentPaths |
        Sort-Object -Unique
)
foreach ($representation in @('lf', 'crlf')) {
    $mirrorRoot = Join-Path $mirrorSessionRoot $representation
    foreach ($relativePath in $mirrorResources) {
        $sourcePath = Join-Path $repositoryRoot $relativePath
        $mirrorPath = Join-Path $mirrorRoot $relativePath
        $null = New-Item -ItemType Directory -Path (Split-Path -Parent $mirrorPath) -Force
        $lfText = [System.Text.UTF8Encoding]::new($false, $true).GetString((Get-Utf8LfBytes $sourcePath))
        $representedText = if ($representation -eq 'crlf') { $lfText -replace "`n", "`r`n" } else { $lfText }
        [System.IO.File]::WriteAllText($mirrorPath, $representedText, [System.Text.UTF8Encoding]::new($false))
    }
    $mirrorBuild = & (Join-Path $mirrorRoot 'build/Build.ps1') `
        -OutputPath (Join-Path $mirrorRoot 'artifacts/WIN-PCInfo.ps1')
    $mirrorBytes = [System.IO.File]::ReadAllBytes($mirrorBuild.outputPath)
    Assert-True ([System.Linq.Enumerable]::SequenceEqual[byte]($firstBytes, $mirrorBytes)) `
        "$representation input trees of the same reviewed text must generate identical application bytes"
    if ($representation -eq 'crlf') { $relocatedCandidatePath = $mirrorBuild.outputPath }
}
. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$relocated = Invoke-GeneratedApplication -CandidatePath $relocatedCandidatePath -Arguments @(
    '-Mode','Automation','-RequestPath',(Join-Path $PSScriptRoot 'fixtures/automation-request.json'),
    '-AcceptPreparation','-PreparationFixturePath',(Join-Path $PSScriptRoot 'fixtures/preparation-ready.json'),
    '-DeviceReadinessFixturePath',(Join-Path $PSScriptRoot 'fixtures/device-complete.json')
)
Assert-True ($relocated.ExitCode -eq 0) `
    'a relocated generated artifact uses its embedded Device Readiness policy without repository sidecars'
Assert-True (@($relocated.Records | Where-Object {
    $_.recordType -eq 'win-pcinfo.device-readiness-validation'
}).Count -eq 1) `
    'the relocated artifact completes the public Device Readiness seam'
$standaloneSoftware = Invoke-GeneratedApplication -CandidatePath $firstPath -Arguments @(
    '-Mode','Automation','-RequestPath',(Join-Path $PSScriptRoot 'fixtures/automation-request.json'),
    '-AcceptPreparation','-PreparationFixturePath',(Join-Path $PSScriptRoot 'fixtures/preparation-ready.json'),
    '-SoftwareInventoryFixturePath',(Join-Path $PSScriptRoot 'fixtures/software-inventory/registry-views.json')
)
Assert-True ($standaloneSoftware.ExitCode -eq 10) `
    'a generated artifact outside an adjacent resource tree uses embedded Software Inventory policy bytes'
Assert-True (@($standaloneSoftware.Records | Where-Object {
    $_.recordType -eq 'win-pcinfo.software-inventory-validation' -and $_.assessmentRecordValidated
}).Count -eq 1) `
    'standalone Software Inventory completes record, report, package, and cleanup validation'
$standaloneCertificate = Invoke-GeneratedApplication -CandidatePath $firstPath -Arguments @(
    '-Mode','Automation','-RequestPath',(Join-Path $PSScriptRoot 'fixtures/automation-request.json'),
    '-AcceptPreparation','-PreparationFixturePath',(Join-Path $PSScriptRoot 'fixtures/preparation-ready.json'),
    '-CertificateTrustFixturePath',(Join-Path $PSScriptRoot 'fixtures/certificate-trust/valid-trusted.json')
)
Assert-True ($standaloneCertificate.ExitCode -eq 10) `
    'a generated artifact outside an adjacent resource tree uses embedded Certificate Trust policy bytes'
Assert-True (@($standaloneCertificate.Records | Where-Object {
    $_.recordType -eq 'win-pcinfo.certificate-trust-validation' -and $_.assessmentRecordValidated
}).Count -eq 1) `
    'standalone Certificate Trust completes record, report, package, and cleanup validation'
Assert-True ($firstBytes[0] -eq 0xEF -and $firstBytes[1] -eq 0xBB -and $firstBytes[2] -eq 0xBF) `
    'the signing representation starts with a UTF-8 BOM'

$textWithoutBom = [System.Text.UTF8Encoding]::new($false, $true).GetString($firstBytes[3..($firstBytes.Length - 1)])
Assert-True ($textWithoutBom -notmatch '(?<!\r)\n') 'the signing representation uses CRLF only'

Write-Output "PASS: deterministic build produced $($first.sha256) with exact source provenance."
