[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-True {
    param([bool] $Condition, [string] $Because)
    if (-not $Condition) { throw "Assertion failed: $Because" }
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$buildScript = Join-Path $repositoryRoot 'build/Build.ps1'
$outputDirectory = Join-Path $repositoryRoot '.test-output/build-determinism'
$firstPath = Join-Path $outputDirectory 'first/WIN-PCInfo.ps1'
$secondPath = Join-Path $outputDirectory 'second/WIN-PCInfo.ps1'

$first = & $buildScript -OutputPath $firstPath
$second = & $buildScript -OutputPath $secondPath
$firstBytes = [System.IO.File]::ReadAllBytes($firstPath)
$secondBytes = [System.IO.File]::ReadAllBytes($secondPath)

Assert-True ([System.Linq.Enumerable]::SequenceEqual[byte]($firstBytes, $secondBytes)) `
    'the same modular source must produce identical generated bytes in different output directories'
Assert-True ($first.sha256 -eq $second.sha256) 'the deterministic artifact digest must agree'
Assert-True ($first.buildContract -eq 'win-pcinfo.build-evidence/1.0.0') 'build evidence is versioned'
Assert-True ($first.buildTool.path -eq 'build/Build.ps1') 'the build tool has a normalized repository identity'
Assert-True ($first.buildTool.sha256 -match '^[0-9a-f]{64}$') 'the build tool digest is exact'
Assert-True ($first.sourceInputs.Count -eq 7) 'every modular source input is recorded'
Assert-True (@($first.sourceInputs | Where-Object { $_.sha256 -notmatch '^[0-9a-f]{64}$' }).Count -eq 0) `
    'every modular source input has an exact digest'
Assert-True ($first.definitionInputs.Count -eq 2) 'both governing preparation resources are recorded'
Assert-True (@($first.definitionInputs | Where-Object { $_.sha256 -notmatch '^[0-9a-f]{64}$' }).Count -eq 0) `
    'every governing preparation resource has an exact digest'
Assert-True ($firstBytes[0] -eq 0xEF -and $firstBytes[1] -eq 0xBB -and $firstBytes[2] -eq 0xBF) `
    'the signing representation starts with a UTF-8 BOM'

$textWithoutBom = [System.Text.UTF8Encoding]::new($false, $true).GetString($firstBytes[3..($firstBytes.Length - 1)])
Assert-True ($textWithoutBom -notmatch '(?<!\r)\n') 'the signing representation uses CRLF only'

Write-Output "PASS: deterministic build produced $($first.sha256) with exact source provenance."
